package Universidadejemplo.Vistas;

import Universidadejemplo.AccesoADatos.MateriaData;
import Universidadejemplo.Entidades.Materia;
import javax.swing.JOptionPane;

public class GestionMaterias extends javax.swing.JInternalFrame {

    MateriaData materiaD;
    Materia materia;
    

    /**
     * Creates new form GestionMaterias
     */
    public GestionMaterias() {
        initComponents();
        this.materiaD = new MateriaData();
        this.materia = new Materia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAlumno = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLAño = new javax.swing.JLabel();
        jTextFieldAño = new javax.swing.JTextField();
        jLEstado = new javax.swing.JLabel();
        jRadioButtonEstado = new javax.swing.JRadioButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Gestión de Materias");
        setPreferredSize(new java.awt.Dimension(400, 400));

        jLAlumno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLAlumno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLAlumno.setText("MATERIA");
        jLAlumno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));

        jLId.setText("Código:");

        jTextFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIdActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLNombre.setText("Nombre:");

        jTextFieldNombre.setEditable(false);
        jTextFieldNombre.setEnabled(false);
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });

        jLAño.setText("Año:");

        jTextFieldAño.setEditable(false);
        jTextFieldAño.setEnabled(false);
        jTextFieldAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAñoActionPerformed(evt);
            }
        });

        jLEstado.setText("Estado:");

        jRadioButtonEstado.setEnabled(false);
        jRadioButtonEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEstadoActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setEnabled(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setEnabled(false);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLAlumno)
                .addGap(153, 153, 153))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(jButtonBuscar)
                        .addGap(32, 32, 32))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLAño)
                                    .addComponent(jLNombre)
                                    .addComponent(jLEstado))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonEstado)
                                    .addComponent(jTextFieldAño, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonLimpiar)
                                .addGap(26, 26, 26)
                                .addComponent(jButtonEliminar)
                                .addGap(34, 34, 34)
                                .addComponent(jButtonGuardar)
                                .addGap(25, 25, 25)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLAlumno)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLId)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNombre)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLAño)
                    .addComponent(jTextFieldAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButtonEstado)
                    .addComponent(jLEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonEliminar)
                    .addComponent(jButtonGuardar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonEstadoActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed

        jTextFieldId.setText("");
        jTextFieldId.setEditable(true);
        jTextFieldNombre.setText("");
        jTextFieldNombre.setEnabled(false);
        jTextFieldAño.setText("");
        jTextFieldAño.setEnabled(false);
        jRadioButtonEstado.setEnabled(false);
        jRadioButtonEstado.setSelected(false);
        
        jButtonGuardar.setEnabled(false);
        jButtonEliminar.setEnabled(false);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTextFieldIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIdActionPerformed

    }//GEN-LAST:event_jTextFieldIdActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        try {
            //Al usar el botón para dos funciones tenemos que hacer la diferenciación
            int id = Integer.parseInt(jTextFieldId.getText());

            if (materia != null) {
                String textNombre = jTextFieldNombre.getText();
                int textAño = Integer.parseInt(jTextFieldAño.getText());
                
                if (jTextFieldNombre.getText().isEmpty() || jTextFieldAño.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this, "No pueden haber campos vacios. ");
                    return;
                }
                boolean estado = jRadioButtonEstado.isSelected();
                if (!materia.getNombre().equalsIgnoreCase(textNombre) || materia.getAño() != textAño || materia.isEstado() != estado) {
                    materiaD.modificarMateria(new Materia(id, textNombre, textAño, estado));
                }else{
                    JOptionPane.showMessageDialog(this, "No existen modificaciones a guardar.");
                }
            } else {
                String nombre = jTextFieldNombre.getText();
                int año = Integer.parseInt(jTextFieldAño.getText());
                boolean estado = jRadioButtonEstado.isSelected();

                materiaD.guardarMateria(new Materia(nombre, año, estado));
            }

            jButtonLimpiarActionPerformed(evt);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this, "Los datos ingresados no son correctos. ");
        }
        
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        try {
            int id = Integer.parseInt(jTextFieldId.getText());
            materia = materiaD.buscarMateriaPorId(id);

            jTextFieldNombre.setEnabled(true);
            jTextFieldNombre.setEditable(true);

            jTextFieldAño.setEnabled(true);
            jTextFieldAño.setEditable(true);

            jButtonGuardar.setEnabled(true);
            jTextFieldId.setEditable(false);
            if (materia != null) {
                jTextFieldNombre.setText(materia.getNombre());
                jTextFieldAño.setText("" + materia.getAño());

                if (materia.isEstado()) {
                    jRadioButtonEstado.setEnabled(false);
                    jRadioButtonEstado.setSelected(materia.isEstado());
                    jButtonEliminar.setEnabled(materia.isEstado());
                } else {
                    jRadioButtonEstado.setEnabled(true);
                    jRadioButtonEstado.setSelected(materia.isEstado());
                    jButtonEliminar.setEnabled(materia.isEstado());
                }
            }else{
                jRadioButtonEstado.setEnabled(true);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Formato de ID inválido. ");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        int id = Integer.parseInt(jTextFieldId.getText());
        int respuesta = JOptionPane.showConfirmDialog(this, "¿ Desea eliminar la materia "+materia.getNombre()+" "+materia.getAño()+" ? ", "Eliminar materia ", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            materiaD.eliminarMateria(id);
            jButtonLimpiarActionPerformed(evt);
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAñoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JLabel jLAlumno;
    private javax.swing.JLabel jLAño;
    private javax.swing.JLabel jLEstado;
    private javax.swing.JLabel jLId;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JRadioButton jRadioButtonEstado;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldAño;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
